pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Automatic merge dependency update PRs if test passed
    conditions:
      - author=github-scx
      - "status-success=ci/circleci: test"
      - body~=labels:.*semver(-patch|-minor)
      - label=dependency
    actions:
      merge:
        method: merge
  - name: Label dependency update PRs
    conditions:
      - author=github-scx
      - body~=.*library-update
    actions:
      label:
        add:
          - dependency